= Component Versions

:description: This document lists the version of every component of the system.
:toclevels: 2
:sectnums:
:icons: font
:nofooter:
:imagesdir: ./images

[IMPORTANT]
====
This page is automatically updated, so please *do not* update manually.
====

== List of component versions

=== Apps

|===
| Component | AppStore (iOS) | PlayStore (Android)

| Maps
a| checkversion:apps[component="maps" stage="appstore"]
a| checkversion:apps[component="maps" stage="playstore"]
|===

=== Backends

|===
| Component | DEV | Test | Staging | Prod

h| Blog
a| checkversion:backends[component="blog" stage="dev"]
a| checkversion:backends[component="blog" stage="test"]
a| checkversion:backends[component="blog" stage="staging"]
a| checkversion:backends[component="blog" stage="prod"]

h| Redmine
a| checkversion:backends[component="redmine" stage="dev"]
a| checkversion:backends[component="redmine" stage="test"]
a| checkversion:backends[component="redmine" stage="staging"]
a| checkversion:backends[component="redmine" stage="prod"]
|===

[subs="attributes"]
----
Last update: {localdatetime}
----
